# Generated by Django 4.0.8 on 2022-11-16 20:00

import akarpov.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=akarpov.utils.files.user_file_upload_mixin),
        ),
        migrations.AddField(
            model_name='user',
            name='image_cropped',
            field=models.ImageField(blank=True, upload_to='cropped/'),
        ),
    ]
