# Generated by Django 4.1.7 on 2023-03-15 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_short_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="short_link",
        ),
    ]
