# Generated by Django 4.2 on 2023-04-10 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_left_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="left_file_upload",
            field=models.BigIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Left file upload(in bites)",
            ),
        ),
    ]
