# Generated by Django 4.2.2 on 2023-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_userhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="userhistory",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
