# Generated by Django 4.2.8 on 2023-12-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_user_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="agree_data_to_be_sold",
            field=models.BooleanField(default=False),
        ),
    ]
