# Generated by Django 4.2.8 on 2024-01-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_agree_data_to_be_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="agree_data_to_be_sold",
            field=models.BooleanField(
                default=False, verbose_name="Agree my data to be sold to vendors"
            ),
        ),
    ]
