# Generated by Django 4.2.10 on 2024-03-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_userapitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapitoken",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
