# Generated by Django 4.2.10 on 2024-03-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_userapitoken_last_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapitoken",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
