# Generated by Django 4.0.8 on 2022-11-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-rating", "-created"]},
        ),
    ]
