# Generated by Django 4.2 on 2023-04-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
