# Generated by Django 4.2.2 on 2023-07-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-rating", "-created"], "verbose_name": "Comment"},
        ),
        migrations.AlterModelOptions(
            name="commentrating",
            options={"verbose_name": "Comment rating"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"], "verbose_name": "Post"},
        ),
        migrations.AlterModelOptions(
            name="postrating",
            options={"verbose_name": "Post rating"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag"},
        ),
    ]
