# Generated by Django 4.2.3 on 2023-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_options_alter_commentrating_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="seo_tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
