# Generated by Django 4.2.8 on 2024-01-14 12:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#FF0000",
                image_field=None,
                max_length=25,
                samples=None,
            ),
        ),
    ]
