# Generated by Django 4.2.3 on 2023-08-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0003_linkviewmeta_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="linkviewmeta",
            options={"ordering": ["-viewed"]},
        ),
    ]
