# Generated by Django 4.1.7 on 2023-02-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="time_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="selectanswerquestion",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="test_platform.selectquestion",
            ),
            preserve_default=False,
        ),
    ]
