# Generated by Django 4.1.7 on 2023-02-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_platform", "0002_form_time_since_selectanswerquestion_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numberrangequestion",
            name="number_range_max",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="numberrangequestion",
            name="number_range_min",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="selectquestion",
            name="max_required_answers",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="selectquestion",
            name="min_required_answers",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="textquestion",
            name="answer_should_contain",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="textquestion",
            name="answer_should_not_contain",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="textquestion",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
