# Generated by Django 4.1.7 on 2023-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_platform", "0004_alter_numberquestion_correct_answer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basequestion",
            options={},
        ),
        migrations.AddField(
            model_name="basequestion",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="basequestion",
            unique_together={("form", "order")},
        ),
    ]
