# Generated by Django 4.2.2 on 2023-07-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_platform", "0007_alter_form_short_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="form",
            options={"verbose_name": "Form"},
        ),
    ]
