# Generated by Django 4.2.8 on 2024-01-14 12:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("themes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
