# Generated by Django 4.0.8 on 2022-12-06 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipeliner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseblock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseblock',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='baseblock',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pipeliner.baseblock'),
        ),
        migrations.AddField(
            model_name='baseblock',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
