# Generated by Django 4.0.8 on 2022-12-07 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pipeliner', '0003_constantnumberblock_constantstringblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplicationBlock',
            fields=[
                ('baseblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeliner.baseblock')),
                ('by', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pipeliner.baseblock',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='constantstringblock',
            name='string',
            field=models.TextField(default='wf'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrashBlock',
            fields=[
                ('baseblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pipeliner.baseblock')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeliner.storage')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pipeliner.baseblock',),
        ),
    ]
