# Generated by Django 4.1.7 on 2023-03-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
        ("files", "0003_basefile_short_link_folder_short_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefile",
            name="short_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shortener.link",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="short_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shortener.link",
            ),
        ),
    ]
