# Generated by Django 4.1.7 on 2023-03-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_alter_basefile_short_link_alter_folder_short_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="basefile",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="files.folder",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="files.folder",
            ),
        ),
    ]
