# Generated by Django 4.1.7 on 2023-03-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_basefile_description_alter_basefile_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefile",
            name="slug",
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
