# Generated by Django 4.1.7 on 2023-03-27 14:57

import akarpov.contrib.chunked_upload.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_file_alter_folder_parent_delete_basefile_file_folder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="completed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="filename",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="offset",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="file",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Uploading"), (2, "Complete")], default=1
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="upload_id",
            field=models.CharField(
                default=akarpov.contrib.chunked_upload.models.generate_upload_id,
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
