# Generated by Django 4.2 on 2023-04-06 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0008_file_completed_on_file_created_on_file_filename_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="completed_on",
        ),
        migrations.RemoveField(
            model_name="file",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="file",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="file",
            name="offset",
        ),
        migrations.RemoveField(
            model_name="file",
            name="status",
        ),
        migrations.RemoveField(
            model_name="file",
            name="upload_id",
        ),
    ]
