# Generated by Django 4.2 on 2023-04-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0012_alter_file_options_alter_file_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["-modified"]},
        ),
    ]
