# Generated by Django 4.2 on 2023-04-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("files", "0001_squashed_0016_alter_file_file_type_alter_file_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="folder",
            options={"base_manager_name": "objects"},
        ),
        migrations.RenameField(
            model_name="file",
            old_name="file",
            new_name="file_obj",
        ),
        migrations.RemoveField(
            model_name="file",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="file",
            name="id",
        ),
        migrations.RemoveField(
            model_name="folder",
            name="id",
        ),
        migrations.RemoveField(
            model_name="folder",
            name="parent",
        ),
        migrations.CreateModel(
            name="BaseFileItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="files.basefileitem",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="file",
            name="basefileitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="files.basefileitem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="folder",
            name="basefileitem_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="files.basefileitem",
            ),
            preserve_default=False,
        ),
    ]
