# Generated by Django 4.2 on 2023-04-22 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0018_remove_file_created_remove_file_modified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basefileitem",
            options={"ordering": ["-modified"]},
        ),
        migrations.AlterModelOptions(
            name="file",
            options={"base_manager_name": "objects"},
        ),
        migrations.RemoveField(
            model_name="file",
            name="user",
        ),
        migrations.RemoveField(
            model_name="folder",
            name="user",
        ),
        migrations.AddField(
            model_name="basefileitem",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="basefileitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="files.folder",
            ),
        ),
    ]
