# Generated by Django 4.2 on 2023-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0020_folder_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="folder",
            name="private",
            field=models.BooleanField(default=True),
        ),
    ]
