# Generated by Django 4.2 on 2023-04-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0021_folder_amount_folder_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="basefileitem",
            name="download",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="basefileitem",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FileReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="files.file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reported_file",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
