# Generated by Django 4.2 on 2023-04-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0022_basefileitem_download_basefileitem_views_filereport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basefileitem",
            old_name="download",
            new_name="downloads",
        ),
        migrations.RemoveField(
            model_name="filereport",
            name="user",
        ),
    ]
