# Generated by Django 4.2.2 on 2023-07-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0023_rename_download_basefileitem_downloads_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "File"},
        ),
        migrations.AlterModelOptions(
            name="filereport",
            options={"verbose_name": "File report"},
        ),
        migrations.AlterModelOptions(
            name="folder",
            options={"verbose_name": "Folder"},
        ),
    ]
