# Generated by Django 4.2.5 on 2023-09-24 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0024_alter_file_options_alter_filereport_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="notify_user_on_view",
            field=models.BooleanField(
                default=False, verbose_name="Receive notifications on file view"
            ),
        ),
        migrations.AlterField(
            model_name="basefileitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="files.folder",
                verbose_name="Folder",
            ),
        ),
    ]
