# Generated by Django 4.2.5 on 2023-09-16 18:33

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0025_create_vector_ps"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="embeddings",
            field=pgvector.django.VectorField(dimensions=768, null=True),
        ),
    ]
