# Generated by Django 4.2.5 on 2023-09-25 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0025_file_notify_user_on_view_alter_basefileitem_parent"),
        ("files", "0026_file_embeddings"),
    ]

    operations = []
