# Generated by Django 4.2.5 on 2023-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0027_merge_20230925_2023"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content",
            field=models.TextField(default="", max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="lang",
            field=models.CharField(
                choices=[("ru", "ru"), ("en", "en")], default="en", max_length=2
            ),
            preserve_default=False,
        ),
    ]
