# Generated by Django 4.2.6 on 2023-11-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0028_file_content_file_lang"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="embeddings",
        ),
        migrations.RemoveField(
            model_name="file",
            name="lang",
        ),
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.TextField(),
        ),
    ]
