# Generated by Django 4.2.6 on 2023-11-06 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0029_remove_file_embeddings_remove_file_lang_and_more"),
    ]
    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS unaccent;",
            reverse_sql="DROP EXTENSION unaccent;",
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION pg_trgm;",
        ),
    ]
