# Generated by Django 4.2.2 on 2023-07-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlist",
            options={"verbose_name": "Playlist"},
        ),
    ]
