# Generated by Django 4.2.3 on 2023-07-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_playlist_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="author",
        ),
        migrations.RemoveField(
            model_name="songinque",
            name="song",
        ),
        migrations.AddField(
            model_name="song",
            name="authors",
            field=models.ManyToManyField(related_name="songs", to="music.author"),
        ),
        migrations.AddField(
            model_name="songinque",
            name="status",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
