# Generated by Django 4.2.4 on 2023-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0005_radiosong_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempFileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="music_tmp")),
            ],
        ),
    ]
