# Generated by Django 4.2.5 on 2023-09-27 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0006_tempfileupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="songs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
