# Generated by Django 4.2.5 on 2023-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0007_song_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
