# Generated by Django 4.2.5 on 2023-09-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0008_song_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songinque",
            name="name",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="songinque",
            name="status",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
