# Generated by Django 4.2.8 on 2023-12-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0012_album_meta_author_albums_author_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="albums",
        ),
        migrations.AddField(
            model_name="album",
            name="authors",
            field=models.ManyToManyField(related_name="albums", to="music.album"),
        ),
        migrations.AlterField(
            model_name="album",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
