# Generated by Django 4.2.8 on 2023-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0013_remove_author_albums_album_authors_alter_album_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="authors",
            field=models.ManyToManyField(related_name="albums", to="music.author"),
        ),
    ]
