# Generated by Django 4.2.8 on 2024-01-14 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0014_alter_album_authors"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMusicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lastfm_username",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "lastfm_token",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("preferences", models.JSONField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
