# Generated by Django 4.2.8 on 2024-01-15 17:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0015_usermusicprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="volume",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
    ]
