# Generated by Django 4.2.16 on 2026-03-23 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0016_anonmusicuser_song_created_song_volume_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("spotify_client_id", models.CharField(blank=True, max_length=200)),
                ("spotify_client_secret", models.CharField(blank=True, max_length=200)),
                ("proxy_url", models.CharField(blank=True, max_length=500)),
                (
                    "youtube_cookies",
                    models.TextField(
                        blank=True, help_text="Netscape cookie file content"
                    ),
                ),
                ("soundcloud_client_id", models.CharField(blank=True, max_length=200)),
                ("is_default", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="DownloadJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=500)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("spotify", "Spotify"),
                            ("youtube", "Youtube"),
                            ("yandex", "Yandex"),
                            ("soundcloud", "Soundcloud"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("resolving", "Resolving"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rate_limited", "Rate Limited"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("error", models.TextField(blank=True)),
                ("total_tracks", models.IntegerField(default=0)),
                ("processed_tracks", models.IntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("playlist_name", models.CharField(blank=True, max_length=500)),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.downloadconfig",
                    ),
                ),
                (
                    "created_playlist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.playlist",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="DownloadTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500)),
                ("artist_name", models.CharField(blank=True, max_length=500)),
                ("album_name", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("searching", "Searching"),
                            ("downloading", "Downloading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rate_limited", "Rate Limited"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("spotify_url", models.URLField(blank=True, max_length=500)),
                ("youtube_url", models.URLField(blank=True, max_length=500)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="music.downloadjob",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.song",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.DeleteModel(
            name="SongInQue",
        ),
    ]
