# Generated by Django 4.1.7 on 2023-03-24 07:12

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                ("md", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="uploads/images/")),
                ("source_link", models.URLField(blank=True)),
                ("view_link", models.URLField(blank=True)),
            ],
            options={
                "ordering": ("-modified",),
            },
        ),
    ]
