# Generated by Django 4.2.3 on 2023-08-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_projectchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("question", models.CharField(max_length=250)),
                ("link", models.URLField(blank=True, null=True)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ["-ordering"],
            },
        ),
    ]
