# Generated by Django 4.2.1 on 2023-06-21 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("promo", models.CharField(max_length=250, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single", "can be activated only one time, by one user"),
                            (
                                "multiuser",
                                "can be activated many times, but only one time for one user",
                            ),
                            ("multiple", "can be activated multiple times"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("app_name", models.CharField(max_length=250)),
                ("model", models.CharField(max_length=250)),
                ("field", models.CharField(max_length=250)),
                ("value", models.IntegerField()),
                ("message", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PromoCodeActivation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activated", models.DateTimeField(auto_now_add=True)),
                (
                    "promocode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="promocodes.promocode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promocode_activations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
