#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

mkdir /app/staticfiles/
chmod -R +r /app/staticfiles/


python /app/manage.py collectstatic --noinput
python /app/manage.py makemigrations
python /app/manage.py migrate auth
python /app/manage.py migrate

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
