# Generated by Django 4.2 on 2023-05-09 07:10

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="extra_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="image",
            name="image_city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="image_location",
            field=location_field.models.plain.PlainLocationField(
                blank=True, max_length=63, null=True
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "short_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shortener.link",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="image",
            name="tags",
            field=models.ManyToManyField(related_name="images", to="gallery.tag"),
        ),
    ]
