# Generated by Django 4.2.2 on 2023-07-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_image_extra_data_image_image_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"verbose_name": "Collection"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Image"},
        ),
    ]
