# Generated by Django 4.2.6 on 2023-11-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_alter_collection_options_alter_image_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
