# Generated by Django 4.2 on 2023-04-06 10:14

import akarpov.contrib.chunked_upload.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chunked_upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunkedupload",
            name="file",
            field=models.FileField(
                max_length=255,
                upload_to=akarpov.contrib.chunked_upload.settings.default_upload_to,
            ),
        ),
    ]
